version: '2'
services:
  web:
    build: .
    ports:
      - "8080:5000"
    volumes:
      - .:/var/app
    environment:
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    # links:
    #   - mongo
  # mongo:
  #   image: mongo
